version: "3"

services:
  mlb2019:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
  notebook:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code/
    ports:
      - "8888:8888"
    expose:
      - "8888"
    command:
      jupyter notebook --allow-root