version: '3'

services:

  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - 8000:8000
    command: gunicorn -w 1 -b :8000 app:application


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
